webapp/hackathon/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

webapp/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.index, name="home"),
    path('login/', views.login_user, name="login"),
    path('final/', views.goto_final_page, name="final"),
]

webapp/home/models.py
from django.db import models

# Create your models here.

webapp/home/views.py
from django.contrib import messages
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def login_user(request):
    email = request.POST.get('inputEmail')
    password = request.POST.get('inputPassword')
    print(email, password)
    if email == "a@b.com" and password == "123":
        return render(request, 'success_page_1.html')
    else:
        messages.error(request, "Invalid Credentials")
        return render(request, 'index.html')
    
def goto_final_page(request):
    return render(request, 'success_page_2.html')

webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- site metas -->
    <title>Hackathon | {% block title %}{% endblock title %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- unicons -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<!-- body -->

<body>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible fade show mt-2" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <!-- header  -->
    {% block header %}
    <!-- header here -->
    {% endblock header %}
    <!-- end header -->
    <!-- main  -->
    {% block body %}
    <!-- Body here -->
    {% endblock body %}
    <!-- end main -->
    <!-- footer  -->
    {% block footer %}
    <!-- footer here -->
    {% endblock footer %}
    <!-- end footer -->
    <!-- Javascript files-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fdde0d4923.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-R7MSQSE8K4"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'G-R7MSQSE8K4');
    </script>
</body>

</html>

webapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Hello World{% endblock title %}

{% block body %}

<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="form-container p-5">
        <form action="{% url 'home:login' %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="inputEmail" class="form-label">Email address</label>
                <input type="email" class="form-control" id="inputEmail" name="inputEmail" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="inputPassword" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword" name="inputPassword">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock body %}

webapp/templates/success_page_1.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Hello World{% endblock title %}

{% block body %}

<div class="d-flex justify-content-center align-items-center sp-1" style="height: 100vh;">
    <h1>This is Success Page 1</h1>
    <a href="{% url 'home:final' %}" class="btn btn-primary">Go to Success Page 2</a>
</div>
{% endblock body %}

webapp/templates/success_page_2.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Hello World{% endblock title %}

{% block body %}

<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <h1>This is Success Page 2</h1>
</div>
{% endblock body %}